# Generated by Django 2.1.7 on 2019-02-21 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedroom_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='laundry_info',
            field=models.CharField(choices=[('L', 'Laundry'), ('N', 'No Laundry')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='ownership_info',
            field=models.CharField(choices=[('O', 'Owned'), ('A', 'Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone_num',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='square_footage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
