# Generated by Django 2.1.5 on 2019-02-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190221_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='parking_info',
            field=models.CharField(choices=[('P', 'Parking'), ('N', 'No Parking')], default='N', max_length=1),
        ),
    ]
