# Generated by Django 2.1.5 on 2019-03-02 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_parking_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
