# Generated by Django 2.1.5 on 2019-03-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190302_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pictures',
            field=models.TextField(default=''),
        ),
    ]
