# Generated by Django 2.1.5 on 2019-03-24 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190324_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.Listing')),
            ],
        ),
    ]
