# Generated by Django 2.1.7 on 2019-03-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190322_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dummyfield',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(to='listings.Listing'),
        ),
    ]
