# Generated by Django 2.1.5 on 2019-03-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_pics/'),
        ),
    ]
