# Generated by Django 2.1.7 on 2019-03-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190324_0310'),
        ('listings', '0009_auto_20190322_2041'),
    ]

    operations = [
    ]
