# Generated by Django 2.1.7 on 2019-04-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20190325_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
    ]
