# Generated by Django 2.1.5 on 2019-04-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190403_1254'),
        ('listings', '0014_auto_20190401_1337'),
    ]

    operations = [
    ]
