# Generated by Django 2.1.7 on 2019-04-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190401_1337'),
        ('listings', '0014_auto_20190403_1254'),
    ]

    operations = [
    ]
