# Generated by Django 2.1.5 on 2019-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190412_0251'),
        ('listings', '0015_merge_20190408_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_profile_list',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to='users.UserProfile'),
        ),
    ]
