# Generated by Django 2.1.5 on 2019-04-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_merge_20190408_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='user_list',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to='users.UserProfile'),
        ),
    ]
