# Generated by Django 2.1.5 on 2019-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20190412_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
