# Generated by Django 2.1.5 on 2019-04-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20190412_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user_list',
            new_name='user_profile_list',
        ),
    ]
