# Generated by Django 2.1.5 on 2019-04-12 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0017_auto_20190412_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_list',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
