# Generated by Django 2.1.5 on 2019-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
