# Generated by Django 2.1.5 on 2019-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cached_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='cached_longitude',
            field=models.FloatField(default=0),
        ),
    ]
